[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
linker = "./linker-wrapper.sh"
rustflags = [
    "-C", "link-arg=-Tsrc/linker.ld",
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
]
