[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tsrc/linker.ld",
    "-C", "link-arg=--no-pie",
    "-C", "link-arg=-static",
    "-C", "link-arg=-znorelro",
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
]
