[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-Tsrc/linker.ld",
    "-C", "link-arg=--oformat=elf64-x86-64",
    "-C", "link-arg=-static",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-no-pie",
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
    "-C", "target-feature=+soft-float",
]
